#source: site
#destination: _gh_pages
#port: 8080
#GH_ENV: true
#show_drafts: true
#lsi: true
#to checkout which version github page uses
#visit: http://pages.github.com/versions/
markdown: kramdown
kramdown:
  auto_ids: false
  #input: GFM
#markdown: redcarpet 
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "table", "with_toc_data", "hard_wrap", "prettify"]

#http://www.emoji-cheat-sheet.com/
#gems: [ jemoji ]
pygments: true 
timezone: Asia/Hong_Kong
encoding: UTF-8
paginate: 5
#safe: true
excerpt_separator: <!--more-->
relative_permalinks: false
permalink: /blog/:year-:month-:day-:title.html
repository: https://github.com/shiedman/shiedman.github.io
#site url is used in sitemap.xml, set it to custom domain name or <username>.github.io
site_url : http://shiedman.github.io

title : Read and Note
#tagline: my private sticky notes 
author :
  name : shiedman
  email : shiedman@gmail.com
  github : shiedman
  twitter : shiedman 

disqus:
  short_name: shiedman #required for post comments
#google analytics
analytics :
  track_id : UA-42488290-1
  track_site: shiedman.github.io


exclude: ["makefile",".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "nohup.out"]
